/* ------------------------------------------------------------------
   Copy for the four policy pages.

   Each page is a flat sequence of blocks:
     ["h2", text, id]  — a section heading, id matched by the page TOC
     ["p", text]        — a paragraph
     ["ul" | "ol", []]  — a list

   Inline markup inside text uses two markers, rendered by
   <LegalBlocks>: **bold** and [[label|href]] for a link.
------------------------------------------------------------------- */

export const LEGAL_PAGES = {

  "privacy-policy": {
    relatedHeading: "Related Policies and Guidance",
    related: [
      ["Terms & Conditions", "/terms-and-conditions"],
      ["Refund & Cancellation Policy", "/refund-cancellation-policy"],
      ["Disclaimer", "/disclaimer"],
      ["Child Safeguarding Policy", "/child-safeguarding-policy/"],
      ["Photo and Video Consent Policy", "/photo-and-video-consent-policy/"],
      ["Accessibility Statement", "/accessibility/"],
    ],
    title: "Privacy Policy | Abacus Experts",
    description: "How Abacus Experts collects, uses and protects parent and student enquiry information.",
    eyebrow: "Abacus Experts legal information",
    h1: "Privacy Policy",
    summary: "This policy explains what information we collect, why we use it, and the choices available to parents and guardians.",
    updated: "Effective date: 2 September 2026 · Last updated: 2 September 2026",
    sections: [
      { id: "who-we-are", label: "Who we are" },
      { id: "information-we-may-collect", label: "Information we may collect" },
      { id: "children-s-information", label: "Children’s information" },
      { id: "how-we-use-information", label: "How we use information" },
      { id: "consent-and-choices", label: "Consent and choices" },
      { id: "sharing-and-service-providers", label: "Sharing and service providers" },
      { id: "retention-and-security", label: "Retention and security" },
      { id: "your-requests", label: "Your requests" },
      { id: "cookies-and-external-services", label: "Cookies and external services" },
      { id: "changes", label: "Changes" },
    ],
    blocks: [
      ["h2", "1. Who we are", "who-we-are"],
      ["p", "Abacus Experts provides classroom abacus training in Hyder Nagar, Hyderabad, and live online classes. For privacy questions, contact [[hello@abacusexperts.com|mailto:hello@abacusexperts.com]] or call [[+91 90325 89990|tel:+919032589990]]."],
      ["h2", "2. Information we may collect", "information-we-may-collect"],
      ["p", "When a parent or guardian sends an enquiry, requests a demo or enrols, we may collect the parent’s name, phone number, email address, Hyderabad area, preferred class format, the child’s age and previous abacus experience, payment and attendance records, and messages shared with our team."],
      ["p", "Please do not send medical records, identity documents or other sensitive information unless we specifically explain why it is required."],
      ["h2", "3. Children’s information", "children-s-information"],
      ["p", "Our services are intended to be arranged by a parent or legal guardian. Children should not submit personal information through this website or WhatsApp without their parent or guardian. We use a child’s limited information only to assess readiness, recommend a level, deliver classes, maintain attendance and progress records, and communicate with the parent or guardian."],
      ["h2", "4. How we use information", "how-we-use-information"],
      ["ul", [
        "Respond to enquiries and schedule demos.",
        "Recommend a programme, level and class format.",
        "Process enrolment, fees, attendance and learning updates.",
        "Provide service messages about batches, class changes and policies.",
        "Maintain security, prevent misuse and meet legal obligations.",
        "Improve our courses and parent support using aggregated feedback.",
      ]],
      ["h2", "5. Consent and choices", "consent-and-choices"],
      ["p", "By contacting us or submitting an enquiry, you ask us to use the information needed to respond. You may withdraw consent for optional communications at any time. Withdrawal does not affect information we must retain for completed payments, dispute handling or legal requirements."],
      ["h2", "6. Sharing and service providers", "sharing-and-service-providers"],
      ["p", "We do not sell personal information. We may share only what is necessary with trainers and authorised staff, payment or accounting providers, website hosting providers, WhatsApp when you choose that channel, Google Maps when you open directions, and professional advisers or authorities when required by law."],
      ["h2", "7. Retention and security", "retention-and-security"],
      ["p", "We retain information only for as long as it is reasonably needed for the enquiry, course delivery, accounts, dispute resolution and legal obligations. We use reasonable administrative and technical safeguards, but no internet or messaging service can guarantee absolute security."],
      ["h2", "8. Your requests", "your-requests"],
      ["p", "A parent or guardian may ask to access, correct or delete information, withdraw optional consent, or raise a grievance by emailing us. We may verify the requester’s identity before acting. Some records may need to be retained where required for accounting, legal or legitimate dispute purposes."],
      ["h2", "9. Cookies and external services", "cookies-and-external-services"],
      ["p", "The current course page does not intentionally use advertising cookies. Essential hosting technology may process basic device and request information. External links such as WhatsApp, Google Maps and research websites have their own privacy practices."],
      ["h2", "10. Changes", "changes"],
      ["p", "We may update this policy when our services or legal requirements change. The latest version and effective date will appear on this page."],
    ],
  },
  "terms-and-conditions": {
    relatedHeading: "Related Policies and Guidance",
    related: [
      ["Privacy Policy", "/privacy-policy"],
      ["Refund & Cancellation Policy", "/refund-cancellation-policy"],
      ["Disclaimer", "/disclaimer"],
      ["Child Safeguarding Policy", "/child-safeguarding-policy/"],
      ["Photo and Video Consent Policy", "/photo-and-video-consent-policy/"],
      ["Accessibility Statement", "/accessibility/"],
    ],
    title: "Terms & Conditions | Abacus Experts",
    description: "Terms governing enquiries, demos, enrolment and abacus classes from Abacus Experts.",
    eyebrow: "Abacus Experts legal information",
    h1: "Terms & Conditions",
    summary: "These terms govern website use, demo bookings, enrolment and participation in Abacus Experts classes.",
    updated: "Effective date: 2 September 2026 · Last updated: 2 September 2026",
    sections: [
      { id: "parent-or-guardian-responsibility", label: "Parent or guardian responsibility" },
      { id: "website-information", label: "Website information" },
      { id: "demo-and-placement", label: "Demo and placement" },
      { id: "enrolment-and-payment", label: "Enrolment and payment" },
      { id: "attendance-and-conduct", label: "Attendance and conduct" },
      { id: "online-classes", label: "Online classes" },
      { id: "missed-and-rescheduled-classes", label: "Missed and rescheduled classes" },
      { id: "learning-outcomes", label: "Learning outcomes" },
      { id: "materials-and-intellectual-property", label: "Materials and intellectual property" },
      { id: "safety-and-safeguarding", label: "Safety and safeguarding" },
      { id: "changes-and-governing-law", label: "Changes and governing law" },
    ],
    blocks: [
      ["h2", "1. Parent or guardian responsibility", "parent-or-guardian-responsibility"],
      ["p", "A parent or legal guardian must arrange and approve services for a child. The parent confirms that information supplied for readiness, placement and enrolment is accurate."],
      ["h2", "2. Website information", "website-information"],
      ["p", "We aim to keep course details accurate, but batch days, timings, seats, fees, trainers and course materials may change. Confirm the current written fee sheet and enrolment details before payment. Website content is general information and is not a guaranteed offer of a seat."],
      ["h2", "3. Demo and placement", "demo-and-placement"],
      ["p", "A free demo or readiness check helps us recommend a suitable pathway and starting level. It does not guarantee admission, a particular trainer, batch, learning result or long-term seat availability."],
      ["h2", "4. Enrolment and payment", "enrolment-and-payment"],
      ["p", "Enrolment is confirmed only after the parent receives the applicable fee sheet and policies, provides required details, pays the stated amount, and receives confirmation from Abacus Experts. Do not pay to an unverified personal account or third party."],
      ["h2", "5. Attendance and conduct", "attendance-and-conduct"],
      ["p", "Students should attend on time, bring the required abacus and materials, follow trainer instructions, and behave respectfully. Parents are responsible for safe travel to classroom sessions and suitable supervision and device setup for online classes."],
      ["h2", "6. Online classes", "online-classes"],
      ["p", "Online participation requires a stable connection, a working camera and a suitable physical abacus. We are not responsible for interruptions caused by a participant’s device, connection or home environment. Recording a class or sharing access links is not permitted unless we give written permission."],
      ["h2", "7. Missed and rescheduled classes", "missed-and-rescheduled-classes"],
      ["p", "Makeup, rescheduling, pause and transfer options depend on the written policy supplied for the selected batch. Trainer illness, safety concerns or operational needs may require us to reschedule a session; we will provide reasonable notice when possible."],
      ["h2", "8. Learning outcomes", "learning-outcomes"],
      ["p", "Progress varies by age, readiness, attendance, practice and individual learning needs. We do not guarantee school marks, IQ improvement, photographic memory, concentration gains, certification results or identical outcomes for every student."],
      ["h2", "9. Materials and intellectual property", "materials-and-intellectual-property"],
      ["p", "Course notes, worksheets, videos, branding and teaching materials are for the enrolled learner’s personal educational use. They may not be copied, sold, uploaded, recorded or distributed without written permission."],
      ["h2", "10. Safety and safeguarding", "safety-and-safeguarding"],
      ["p", "Parents should communicate concerns directly to the centre. We may refuse or pause participation where conduct creates a safety risk, violates another learner’s privacy or seriously disrupts the class."],
      ["h2", "11. Changes and governing law", "changes-and-governing-law"],
      ["p", "We may update these terms prospectively. Confirmed enrolment terms remain subject to the written agreement supplied for that enrolment. These terms are governed by the laws of India, with disputes subject to the appropriate courts in Hyderabad, Telangana, unless applicable law requires otherwise."],
    ],
  },
  "refund-cancellation-policy": {
    relatedHeading: "Related Policies and Guidance",
    related: [
      ["Privacy Policy", "/privacy-policy"],
      ["Terms & Conditions", "/terms-and-conditions"],
      ["Disclaimer", "/disclaimer"],
      ["Child Safeguarding Policy", "/child-safeguarding-policy/"],
      ["Photo and Video Consent Policy", "/photo-and-video-consent-policy/"],
      ["Accessibility Statement", "/accessibility/"],
    ],
    title: "Refund & Cancellation Policy | Abacus Experts",
    description: "How demo cancellations, course cancellations, refunds and transfers are handled by Abacus Experts.",
    eyebrow: "Abacus Experts legal information",
    h1: "Refund & Cancellation Policy",
    summary: "The exact financial terms for your batch will be provided in writing before payment. This page explains the general process.",
    updated: "Effective date: 2 September 2026 · Last updated: 2 September 2026",
    sections: [
      { id: "free-demo-cancellations", label: "Free demo cancellations" },
      { id: "before-making-payment", label: "Before making payment" },
      { id: "cancellation-before-the-course-starts", label: "Cancellation before the course starts" },
      { id: "after-classes-have-started", label: "After classes have started" },
      { id: "changes-made-by-abacus-experts", label: "Changes made by Abacus Experts" },
      { id: "duplicate-or-incorrect-payments", label: "Duplicate or incorrect payments" },
      { id: "how-to-request-cancellation-or-review", label: "How to request cancellation or review" },
      { id: "processing", label: "Processing" },
    ],
    blocks: [
      ["legalnote", "**Important:** No fixed refund percentage or deadline is promised on this page. The written fee sheet and enrolment confirmation for your selected batch will state the applicable terms before you pay."],
      ["h2", "1. Free demo cancellations", "free-demo-cancellations"],
      ["p", "A free demo has no fee. If you cannot attend, please contact us as early as possible so the seat can be offered to another family and a new date can be discussed."],
      ["h2", "2. Before making payment", "before-making-payment"],
      ["p", "Ask for the total tuition, number and duration of classes, material charges, assessment or certificate charges, batch schedule, makeup rules, pause and transfer rules, and the applicable cancellation/refund terms in writing."],
      ["h2", "3. Cancellation before the course starts", "cancellation-before-the-course-starts"],
      ["p", "Send a written request through email or the verified WhatsApp number. Eligibility for a refund and any deductions will follow the written terms supplied with your enrolment. Non-recoverable kit, workbook, payment-processing or administrative costs may be excluded where those terms clearly disclosed them before payment."],
      ["h2", "4. After classes have started", "after-classes-have-started"],
      ["p", "Fees are generally allocated to a reserved small-batch seat, trainer time and materials. Any refund, credit, transfer or pause after commencement will therefore be assessed under the written enrolment policy and the classes or materials already provided. Absence alone does not automatically create a refund entitlement."],
      ["h2", "5. Changes made by Abacus Experts", "changes-made-by-abacus-experts"],
      ["p", "If we cancel a paid programme and cannot provide a reasonable reschedule, transfer or equivalent option, we will communicate the available remedy, including any applicable refund for undelivered services. Temporary class rescheduling does not by itself mean the programme is cancelled."],
      ["h2", "6. Duplicate or incorrect payments", "duplicate-or-incorrect-payments"],
      ["p", "Report a duplicate or incorrect payment promptly with the payment reference. After verification, valid excess payments will be corrected using an appropriate payment method."],
      ["h2", "7. How to request cancellation or review", "how-to-request-cancellation-or-review"],
      ["p", "Email [[hello@abacusexperts.com|mailto:hello@abacusexperts.com]] or WhatsApp [[+91 90325 89990|https://wa.me/919032589990]] with the parent’s name, learner’s batch, payment date, transaction reference and reason for the request. Do not send full bank, card or identity details."],
      ["h2", "8. Processing", "processing"],
      ["p", "We will acknowledge the request, verify the enrolment and payment record, and explain the decision under the written terms. Bank or payment-provider processing time may apply after an approved refund is initiated."],
    ],
  },
  "disclaimer": {
    relatedHeading: "Related Policies and Guidance",
    related: [
      ["Privacy Policy", "/privacy-policy"],
      ["Terms & Conditions", "/terms-and-conditions"],
      ["Refund & Cancellation Policy", "/refund-cancellation-policy"],
      ["Child Safeguarding Policy", "/child-safeguarding-policy/"],
      ["Photo and Video Consent Policy", "/photo-and-video-consent-policy/"],
      ["Accessibility Statement", "/accessibility/"],
    ],
    title: "Disclaimer | Abacus Experts",
    description: "Educational, results, pricing and external-link disclaimer for the Abacus Experts website.",
    eyebrow: "Abacus Experts legal information",
    h1: "Disclaimer",
    summary: "This page explains the limits of the educational and general information published on this website.",
    updated: "Effective date: 2 September 2026 · Last updated: 2 September 2026",
    sections: [
      { id: "educational-information", label: "Educational information" },
      { id: "no-guaranteed-results", label: "No guaranteed results" },
      { id: "current-information", label: "Current information" },
      { id: "research-references", label: "Research references" },
      { id: "external-links-and-services", label: "External links and services" },
      { id: "testimonials-and-comparisons", label: "Testimonials and comparisons" },
      { id: "limitation", label: "Limitation" },
    ],
    blocks: [
      ["h2", "1. Educational information", "educational-information"],
      ["p", "Website content describes abacus and mental-arithmetic training in general terms. It is not a substitute for school teaching, special-education assessment, medical advice, psychological advice or an individual professional evaluation."],
      ["h2", "2. No guaranteed results", "no-guaranteed-results"],
      ["p", "Examples of skills, benefits or progress are not promises. Results vary by readiness, age, attendance, practice, teaching response and other individual factors. Abacus Experts does not guarantee marks, grades, IQ improvement, photographic memory, concentration improvement or the same outcome for every learner."],
      ["h2", "3. Current information", "current-information"],
      ["p", "Fees, seats, schedules, trainers, programme details and policies may change. Always confirm the latest information directly before travelling, enrolling or paying. Placeholder or example information should not be treated as a confirmed offer."],
      ["h2", "4. Research references", "research-references"],
      ["p", "Links to independent research are provided for further reading. A study or review does not prove that every child will receive the reported outcome, and linking does not mean the researchers endorse Abacus Experts."],
      ["h2", "5. External links and services", "external-links-and-services"],
      ["p", "WhatsApp, Google Maps and other external websites are operated by third parties. We do not control their availability, accuracy, privacy practices or content. Opening an external link is your choice."],
      ["h2", "6. Testimonials and comparisons", "testimonials-and-comparisons"],
      ["p", "Any published testimonial reflects that individual’s experience and is not a guarantee. Market comparisons are based on publicly available information at the time reviewed and may change; parents should verify each provider’s current offer directly."],
      ["h2", "7. Limitation", "limitation"],
      ["p", "To the extent permitted by applicable law, Abacus Experts is not responsible for decisions made solely from general website content or for interruptions caused by third-party services. Nothing on this page excludes rights or responsibilities that cannot legally be excluded."],
    ],
  },
};
